#!/usr/bin/env bash
# Apply on the Mac mini as an **administrative** user (must use sudo).
#
# - Binds sshd to loopback + your Tailscale IPv4 only (not LAN/Wi-Fi), so random
#   devices on 192.168.x.x cannot reach SSH.
# - Moves SSH off port 22 to PORT (default 52822).
#
# Prerequisites:
#   - Tailscale installed and logged in on this Mac; ``tailscale ip -4`` must work.
#   - Remote Login (SSH) enabled in System Settings.
#
# Usage (on the Mac mini):
#   chmod +x macmini_apply_sshd_tailscale_only.sh
#   ./macmini_apply_sshd_tailscale_only.sh [PORT] [TAILSCALE_IPV4]
#
# Example:
#   ./macmini_apply_sshd_tailscale_only.sh 52822 100.67.17.9
#
# After running, connect from your Mac:
#   ssh -p PORT -i ~/.ssh/your_mini_key operator@TAILSCALE_IPV4
#
# Recovery: use physical console / Screen Sharing, or fix/delete
#   /etc/ssh/sshd_config.d/200-hermes-tailscale-only.conf
# and restart Remote Login.
#
set -euo pipefail

PORT="${1:-52822}"
TS_IP="${2:-}"
if [[ -z "$TS_IP" ]]; then
  if command -v tailscale >/dev/null 2>&1; then
    TS_IP="$(tailscale ip -4 2>/dev/null | head -1 | tr -d '[:space:]')"
  fi
fi
[[ -n "$TS_IP" ]] || {
  echo "error: set Tailscale IPv4 (arg 2) or install Tailscale and run \`tailscale up\`." >&2
  exit 1
}

CONF="/etc/ssh/sshd_config.d/200-hermes-tailscale-only.conf"

if [[ "$(id -u)" != "0" ]]; then
  echo "error: run with sudo: sudo $0 $PORT $TS_IP" >&2
  exit 1
fi

umask 022
cat >"$CONF" <<EOF
# Generated by macmini_apply_sshd_tailscale_only.sh — SSH only on loopback + Tailscale.
Port ${PORT}
ListenAddress 127.0.0.1
ListenAddress ${TS_IP}
PubkeyAuthentication yes
PasswordAuthentication yes
KbdInteractiveAuthentication yes
EOF
chmod 644 "$CONF"

# Reload OpenSSH (macOS system daemon).
if launchctl kickstart -k system/com.openssh.sshd 2>/dev/null; then
  echo "sshd reloaded via launchctl kickstart."
else
  echo "warning: kickstart failed; toggle Remote Login off/on in System Settings → Sharing." >&2
fi

echo "Wrote ${CONF}"
echo "Listen: 127.0.0.1:${PORT} and ${TS_IP}:${PORT}"
echo "LAN addresses no longer accept SSH (only this Tailscale IP + localhost)."
