"""Load ``provider_model_routing_catalog.json`` and format it for LLM routing prompts.

The catalog (regenerated by ``scripts/generate_provider_model_routing_catalog.py``)
lists provider models with reasoning bands, categories, modalities, and routing
hints. Routing/consultant/delegation code appends the formatted digest so advisors
consider the full model spectrum when choosing tiers or judging delegate fitness.

Environment:
    HERMES_ROUTING_CATALOG_MAX_CHARS — optional cap on digest length (default: no cap).
"""

from __future__ import annotations

import json
import logging
import os
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

_CATALOG_FILENAME = "provider_model_routing_catalog.json"
# Non-chat SKUs: not useful for turn routing / delegation model judgment.
_EXCLUDED_CATEGORIES = frozenset(
    {
        "embedding",
        "moderation",
    }
)

_ROUTING_OUTPUT_RULES = """\
CATALOG USAGE (read-only context):
- Hermes still maps work to tier letters A–G; concrete model IDs come from \
governance ``tier_models`` and runtime config — do not output arbitrary model slugs \
in place of tiers.
- Use reasoning_level, category, modalities, best_for, and relative_latency to \
judge task fit and whether to stay on A/B/C vs escalate toward D/E/F/G.
- OpenAI o-series / ``reasoning_native`` rows imply deliberate chain-of-thought \
workloads — align with harder tiers (typically E/F) when depth is required; \
coding-heavy o-work still favors F over E.
- xAI / Grok and additional Google Gemini rows inform multimodal, latency, and \
cost tradeoffs even when the live tier slug is OpenRouter-style.
"""


@lru_cache(maxsize=1)
def _catalog_path() -> Path:
    return Path(__file__).resolve().parent / "data" / _CATALOG_FILENAME


@lru_cache(maxsize=1)
def load_provider_model_routing_catalog() -> Dict[str, Any]:
    """Parse the JSON catalog; raise if missing or invalid."""
    path = _catalog_path()
    raw = path.read_text(encoding="utf-8")
    data = json.loads(raw)
    if not isinstance(data, dict) or "providers" not in data:
        raise ValueError(f"invalid routing catalog schema: {path}")
    return data


def clear_routing_catalog_cache() -> None:
    """Test hook: invalidate cached path and parsed JSON."""
    _catalog_path.cache_clear()
    load_provider_model_routing_catalog.cache_clear()


def _max_digest_chars() -> Optional[int]:
    raw = (os.environ.get("HERMES_ROUTING_CATALOG_MAX_CHARS") or "").strip()
    if not raw:
        return None
    try:
        n = int(raw, 10)
    except ValueError:
        return None
    return n if n > 0 else None


def _fmt_hints(data: Dict[str, Any]) -> List[str]:
    lines: List[str] = []
    ver = data.get("schema_version")
    snap = data.get("snapshot_date")
    lines.append(f"PROVIDER MODEL CATALOG (schema_version={ver}, snapshot_date={snap})")
    lines.append("")
    scale = data.get("reasoning_level_scale")
    if isinstance(scale, dict) and scale:
        lines.append("reasoning_level_scale:")
        for k, v in scale.items():
            lines.append(f"  {k}: {v}")
        lines.append("")
    hints = data.get("cross_provider_routing_hints")
    if isinstance(hints, list) and hints:
        lines.append("cross_provider_routing_hints:")
        for h in hints:
            if isinstance(h, str) and h.strip():
                lines.append(f"  - {h.strip()}")
        lines.append("")
    lines.append(_ROUTING_OUTPUT_RULES.strip())
    lines.append("")
    return lines


def _fmt_model_line(provider_key: str, m: Dict[str, Any]) -> str:
    mid = str(m.get("id") or "").strip()
    cat = str(m.get("category") or "").strip()
    rl = str(m.get("reasoning_level") or "").strip()
    lat = str(m.get("relative_latency") or "").strip()
    mods = m.get("modalities")
    if isinstance(mods, list):
        mod_s = ",".join(str(x) for x in mods[:6])
    else:
        mod_s = ""
    best = m.get("best_for")
    if isinstance(best, list) and best:
        bf = "; ".join(str(x).strip() for x in best[:4] if str(x).strip())
    else:
        bf = ""
    notes = str(m.get("notes") or "").strip()
    parts = [
        f"{provider_key}/{mid}",
        f"cat={cat}",
        f"rl={rl}",
    ]
    if lat:
        parts.append(f"lat={lat}")
    if mod_s:
        parts.append(f"mod={mod_s}")
    if bf:
        parts.append(f"best_for={bf}")
    if notes and len(notes) < 120:
        parts.append(f"notes={notes}")
    line = " | ".join(parts)
    if len(line) > 280:
        line = line[:277] + "..."
    return line


def _collect_model_lines(data: Dict[str, Any]) -> List[str]:
    providers = data.get("providers")
    if not isinstance(providers, dict):
        return []
    # Stable provider order: openai, anthropic, google, xai, then any others sorted.
    pref = ["openai", "anthropic", "google", "xai"]
    keys = [k for k in pref if k in providers]
    keys.extend(sorted(k for k in providers.keys() if k not in pref))
    out: List[str] = []
    for pk in keys:
        pv = providers.get(pk)
        if not isinstance(pv, dict):
            continue
        models = pv.get("models")
        if not isinstance(models, list):
            continue
        out.append(f"[{pk}]")
        for m in models:
            if not isinstance(m, dict):
                continue
            cat = str(m.get("category") or "").strip()
            if cat in _EXCLUDED_CATEGORIES:
                continue
            out.append(_fmt_model_line(pk, m))
        out.append("")
    return out


def format_routing_catalog_digest(max_chars: Optional[int] = None) -> str:
    """Human-readable block for system prompts (routing, consultant, delegation).

    Omits embedding/moderation rows. Truncates to *max_chars* when set; when None,
    uses ``HERMES_ROUTING_CATALOG_MAX_CHARS`` if set, else no truncation.
    """
    try:
        data = load_provider_model_routing_catalog()
    except Exception as exc:
        logger.warning("provider_model_routing_catalog: load failed: %s", exc)
        return ""

    cap = max_chars if max_chars is not None else _max_digest_chars()

    header = _fmt_hints(data)
    body = _collect_model_lines(data)
    full = "\n".join(header + body).strip()
    if cap is None or len(full) <= cap:
        return full

    # Truncate from the end of model lines while keeping header.
    head_txt = "\n".join(header).strip()
    budget = cap - len(head_txt) - 80
    if budget < 200:
        return head_txt + "\n\n(catalog model list truncated — increase HERMES_ROUTING_CATALOG_MAX_CHARS)"

    kept: List[str] = []
    used = 0
    for line in body:
        if not line.strip():
            if used + 1 <= budget:
                kept.append("")
                used += 1
            continue
        L = len(line) + 1
        if used + L > budget:
            break
        kept.append(line)
        used += L
    return head_txt + "\n\n" + "\n".join(kept).strip() + "\n\n(catalog truncated — set HERMES_ROUTING_CATALOG_MAX_CHARS)"
